[package]
name = "rusty-transcriber"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
hex = "0.4.3"
reqwest = { version = "0.12.24", features = ["blocking"]}
sha2 = "0.10.9"
tempfile = "3.23.0"
